package models

import "fmt"

// NewApp represents the fields required to create a new application entry in the database.
// This struct is used when inserting a new application. It does not include the ID field,
// which is generated by the database upon insertion. Nevertheless, it is almost identical
// to ThisApp. Perhaps in the future, we can merge these two structs into one and use tags
// to differentiate between the two use cases.
type NewApp struct {
	Name    string `json:"name"`
	Release string `json:"release"`
	Path    string `json:"path"`
	Init    string `json:"init"`
	Web     string `json:"web"`
	Title   string `json:"title"`
	Created int64  `json:"created"`
	Updated int64  `json:"updated"`
}

// Error implements error.
func (t NewApp) Error() string {
	return fmt.Sprintf("NewApp error: Name: %s, Release: %s, Path: %s, Init: %s, Web: %s, Title: %s, Created: %d, Updated: %d", t.Name, t.Release, t.Path, t.Init, t.Web, t.Title, t.Created, t.Updated)
}
